from PyQt5 import QtCore, QtGui, QtWidgets

import psycopg2

conn = psycopg2.connect(
    host = 'localhost',
    database = 'postgres',
    user = 'postgres',
    password = 'myhicursed',
    port = '5432'
)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1375, 861)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(430, 30, 921, 801))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 919, 799))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)

        self.scrollLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)

        self.widget.setGeometry(QtCore.QRect(40, 30, 851, 141))
        self.widget.setStyleSheet("background-color: rgb(244, 232, 211);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 20, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(750, 20, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 256, 256))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-33, 290, 461, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 360, 151, 51))
        self.pushButton.setStyleSheet("background-color: rgb(103, 186, 128);")
        self.pushButton.setObjectName("pushButton")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(480, 270, 781, 361))
        self.widget_2.setStyleSheet("background-color: rgb(244, 232, 211);")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 300, 141, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(103, 186, 128);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget1 = QtWidgets.QWidget(self.widget_2)
        self.widget1.setGeometry(QtCore.QRect(140, 20, 491, 261))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 7, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 7, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.OpenAddPartner)
        self.pushButton_2.clicked.connect(self.CreatePartner)

        self.label_6.setPixmap(QtGui.QPixmap("icon.ico"))
        self.widget.hide()
        self.widget_2.hide()
        cursor = conn.cursor()
        cursor.execute("""SELECT partner_type, partner_name, director, telephone, rate 
                                            FROM partners """)
        rows = cursor.fetchall()
        for i, row in enumerate(rows):
            a, b, c, d, e = row
            new_card = self.CreateCard(a, b, c, d, e)
            self.scrollLayout.addWidget(new_card)
        cursor.close()

    def CreatePartner(self):
        p_type = self.lineEdit.text()
        p_name = self.lineEdit_2.text()
        p_director = self.lineEdit_3.text()
        p_email = self.lineEdit_4.text()
        p_telephone = self.lineEdit_5.text()
        p_adress = self.lineEdit_6.text()
        p_inn = self.lineEdit_7.text()
        p_rate = self.lineEdit_8.text()
        if not p_type:
            QtWidgets.QMessageBox.warning(None, "ERROR", "Заполните все поля!")
            return
        try:
            cursor = conn.cursor()
            cursor.execute("""
                            INSERT INTO partners(partner_type, partner_name, director, email, telephone, adress, inn, rate)
                            VALUES(%s, %s, %s, %s, %s, %s, %s, %s)
                """, (p_type, p_name, p_director, p_email, p_telephone, p_adress, p_inn, p_rate))
        except Exception as e:
            print("Не удалось добавить партнера")
        conn.commit()


    def CreateCard(self, a, b, c, d, e):
        card = QtWidgets.QWidget()
        card.setFixedSize(self.widget.size())
        card.setStyleSheet(self.widget.styleSheet())

        label1 = QtWidgets.QLabel(card)
        label1.setGeometry(self.label.geometry())
        label1.setText(f'{a} | {b}')

        label2 = QtWidgets.QLabel(card)
        label2.setGeometry(self.label_2.geometry())
        label2.setText(c)

        label3 = QtWidgets.QLabel(card)
        label3.setGeometry(self.label_3.geometry())
        label3.setText(d)

        label4 = QtWidgets.QLabel(card)
        label4.setGeometry(self.label_4.geometry())
        label4.setText("")

        label5 = QtWidgets.QLabel(card)
        label5.setGeometry(self.label_5.geometry())
        label5.setText(f'Рейтинг: {e}')
        return card

    def OpenAddPartner(self):
        self.widget_2.setVisible(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Тип | Партнер"))
        self.label_2.setText(_translate("MainWindow", "Директор"))
        self.label_3.setText(_translate("MainWindow", "Телефон"))
        self.label_4.setText(_translate("MainWindow", "%"))
        self.label_5.setText(_translate("MainWindow", "Рейтинг"))
        self.pushButton.setText(_translate("MainWindow", "Добавить партнера"))
        self.pushButton_2.setText(_translate("MainWindow", "Создать"))
        self.label_7.setText(_translate("MainWindow", "Тип"))
        self.label_8.setText(_translate("MainWindow", "Партнер"))
        self.label_9.setText(_translate("MainWindow", "Директор"))
        self.label_10.setText(_translate("MainWindow", "email"))
        self.label_11.setText(_translate("MainWindow", "Телефон"))
        self.label_12.setText(_translate("MainWindow", "Адрес"))
        self.label_13.setText(_translate("MainWindow", "ИНН"))
        self.label_14.setText(_translate("MainWindow", "Рейтинг"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
