from PyQt5 import QtCore, QtGui, QtWidgets
import psycopg2



conn = psycopg2.connect(
            host = 'localhost',
            database = 'postgres',
            user = 'postgres',
            password = 'myhicursed',
            port = '5432'
        )

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1294, 889)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(350, 10, 931, 861))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 929, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 500))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"border: 1px solid black;")
        self.widget.setObjectName("widget")
        self.label_56 = QtWidgets.QLabel(self.widget)
        self.label_56.setGeometry(QtCore.QRect(10, 50, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("border: 0px solid black;")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.widget)
        self.label_57.setGeometry(QtCore.QRect(650, 20, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("border: 0px solid black;")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.widget)
        self.label_58.setGeometry(QtCore.QRect(10, 70, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("border: 0px solid black;")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.widget)
        self.label_59.setGeometry(QtCore.QRect(10, 10, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("border: 0px solid black;")
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.widget)
        self.label_60.setGeometry(QtCore.QRect(10, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("border: 0px solid black;")
        self.label_60.setObjectName("label_60")
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_2.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"border: 1px solid black;")
        self.widget_2.setObjectName("widget_2")
        self.label_61 = QtWidgets.QLabel(self.widget_2)
        self.label_61.setGeometry(QtCore.QRect(10, 50, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("border: 0px solid black;")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.widget_2)
        self.label_62.setGeometry(QtCore.QRect(650, 20, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("border: 0px solid black;")
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.widget_2)
        self.label_63.setGeometry(QtCore.QRect(10, 70, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("border: 0px solid black;")
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.widget_2)
        self.label_64.setGeometry(QtCore.QRect(10, 10, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("border: 0px solid black;")
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.widget_2)
        self.label_65.setGeometry(QtCore.QRect(10, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("border: 0px solid black;")
        self.label_65.setObjectName("label_65")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_5.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"border: 1px solid black;")
        self.widget_5.setObjectName("widget_5")
        self.label_76 = QtWidgets.QLabel(self.widget_5)
        self.label_76.setGeometry(QtCore.QRect(10, 50, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_76.setFont(font)
        self.label_76.setStyleSheet("border: 0px solid black;")
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.widget_5)
        self.label_77.setGeometry(QtCore.QRect(650, 20, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_77.setFont(font)
        self.label_77.setStyleSheet("border: 0px solid black;")
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.widget_5)
        self.label_78.setGeometry(QtCore.QRect(10, 70, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("border: 0px solid black;")
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.widget_5)
        self.label_79.setGeometry(QtCore.QRect(10, 10, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_79.setFont(font)
        self.label_79.setStyleSheet("border: 0px solid black;")
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.widget_5)
        self.label_80.setGeometry(QtCore.QRect(10, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_80.setFont(font)
        self.label_80.setStyleSheet("border: 0px solid black;")
        self.label_80.setObjectName("label_80")
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_3.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"border: 1px solid black;")
        self.widget_3.setObjectName("widget_3")
        self.label_66 = QtWidgets.QLabel(self.widget_3)
        self.label_66.setGeometry(QtCore.QRect(10, 50, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("border: 0px solid black;")
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.widget_3)
        self.label_67.setGeometry(QtCore.QRect(650, 20, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("border: 0px solid black;")
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.widget_3)
        self.label_68.setGeometry(QtCore.QRect(10, 70, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("border: 0px solid black;")
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.widget_3)
        self.label_69.setGeometry(QtCore.QRect(10, 10, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("border: 0px solid black;")
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.widget_3)
        self.label_70.setGeometry(QtCore.QRect(10, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_70.setFont(font)
        self.label_70.setStyleSheet("border: 0px solid black;")
        self.label_70.setObjectName("label_70")
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_4.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"border: 1px solid black;")
        self.widget_4.setObjectName("widget_4")
        self.label_71 = QtWidgets.QLabel(self.widget_4)
        self.label_71.setGeometry(QtCore.QRect(10, 50, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setStyleSheet("border: 0px solid black;")
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.widget_4)
        self.label_72.setGeometry(QtCore.QRect(650, 20, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("border: 0px solid black;")
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.widget_4)
        self.label_73.setGeometry(QtCore.QRect(10, 70, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("border: 0px solid black;")
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.widget_4)
        self.label_74.setGeometry(QtCore.QRect(10, 10, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setStyleSheet("border: 0px solid black;")
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.widget_4)
        self.label_75.setGeometry(QtCore.QRect(10, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_75.setFont(font)
        self.label_75.setStyleSheet("border: 0px solid black;")
        self.label_75.setObjectName("label_75")
        self.verticalLayout_2.addWidget(self.widget_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(340, -30, 20, 961))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 820, 101, 51))
        self.pushButton.setStyleSheet("background-color: rgb(103, 186, 128);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 256, 256))
        self.label.setText("")
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 290, 351, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.label.setPixmap(QtGui.QPixmap("icon.ico"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.ShowAllPartners()

    def ShowAllPartners(self):
        cards = [
            [self.label_59, self.label_60, self.label_56, self.label_58, self.label_57],
            [self.label_64, self.label_65, self.label_61, self.label_63, self.label_62],
            [self.label_79, self.label_80, self.label_76, self.label_78, self.label_77],
            [self.label_69, self.label_70, self.label_66, self.label_68, self.label_67],
            [self.label_74, self.label_75, self.label_71, self.label_73, self.label_72]

        ]
        cursor = conn.cursor()

        cursor.execute("SELECT partner_type, partner_name, director, telephone, rate FROM partners")
        rows = cursor.fetchall()


        for i, row in enumerate(rows):
            if i >= len(cards):
                break
            pt, pn, dn, tp, rt = row
            print(pt)
            cursor.execute("SELECT SUM(products_amount) FROM partner_products WHERE partner_name = %s",(pn,))
            sm = cursor.fetchone()
            if sm[0] < 10000:
                res = 0
            elif 10000 < sm[0] < 50000:
                res = 5
            elif 50000 < sm[0] < 300000:
                res = 10
            else:
                res = 15
            cards[i][0].setText(f'{pt} | {pn}')
            cards[i][1].setText(dn)
            cards[i][2].setText(f'+7 {tp}')
            cards[i][3].setText(f'Рейтинг: {rt}')
            cards[i][4].setText(f'{res}%')




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_56.setText(_translate("MainWindow", "+7 223 322 22 32"))
        self.label_57.setText(_translate("MainWindow", "10%"))
        self.label_58.setText(_translate("MainWindow", "Рейтинг: 10"))
        self.label_59.setText(_translate("MainWindow", "Тип | Наименование партнера"))
        self.label_60.setText(_translate("MainWindow", "Директор"))
        self.label_61.setText(_translate("MainWindow", "+7 223 322 22 32"))
        self.label_62.setText(_translate("MainWindow", "10%"))
        self.label_63.setText(_translate("MainWindow", "Рейтинг: 10"))
        self.label_64.setText(_translate("MainWindow", "Тип | Наименование партнера"))
        self.label_65.setText(_translate("MainWindow", "Директор"))
        self.label_76.setText(_translate("MainWindow", "+7 223 322 22 32"))
        self.label_77.setText(_translate("MainWindow", "10%"))
        self.label_78.setText(_translate("MainWindow", "Рейтинг: 10"))
        self.label_79.setText(_translate("MainWindow", "Тип | Наименование партнера"))
        self.label_80.setText(_translate("MainWindow", "Директор"))
        self.label_66.setText(_translate("MainWindow", "+7 223 322 22 32"))
        self.label_67.setText(_translate("MainWindow", "10%"))
        self.label_68.setText(_translate("MainWindow", "Рейтинг: 10"))
        self.label_69.setText(_translate("MainWindow", "Тип | Наименование партнера"))
        self.label_70.setText(_translate("MainWindow", "Директор"))
        self.label_71.setText(_translate("MainWindow", "+7 223 322 22 32"))
        self.label_72.setText(_translate("MainWindow", "10%"))
        self.label_73.setText(_translate("MainWindow", "Рейтинг: 10"))
        self.label_74.setText(_translate("MainWindow", "Тип | Наименование партнера"))
        self.label_75.setText(_translate("MainWindow", "Директор"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
