# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(2952, 1547)
        MainWindow.setStyleSheet("background-color: rgb(246, 242, 235);\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(110, 0, 41, 801))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(130, 60, 881, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 70, 131, 731))
        self.widget.setStyleSheet("background-color: rgb(44, 54, 57);\n"
"border: none;\n"
"border-right: 2px solid rgb(68, 89, 90);\n"
"padding: 15px;")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(0, 460, 121, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 510, 121, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 560, 121, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 610, 121, 41))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButtonMain = QtWidgets.QPushButton(self.widget)
        self.pushButtonMain.setGeometry(QtCore.QRect(0, 20, 121, 41))
        self.pushButtonMain.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}")
        self.pushButtonMain.setObjectName("pushButtonMain")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1001, 81))
        self.widget_2.setStyleSheet("background-color: rgb(68, 89, 90);\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(246, 242, 235);\n"
"    font-size: 24px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(200, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(246, 242, 235);\n"
"    font-size: 24px;")
        self.label_2.setObjectName("label_2")
        self.line_3 = QtWidgets.QFrame(self.widget_2)
        self.line_3.setGeometry(QtCore.QRect(161, 10, 31, 61))
        self.line_3.setStyleSheet("")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(740, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(246, 242, 235);\n"
"    font-size: 24px;")
        self.label_3.setObjectName("label_3")
        self.line_4 = QtWidgets.QFrame(self.widget_2)
        self.line_4.setGeometry(QtCore.QRect(830, 0, 20, 71))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(880, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(246, 242, 235);\n"
"    font-size: 24px;")
        self.label_4.setObjectName("label_4")
        self.line_5 = QtWidgets.QFrame(self.widget_2)
        self.line_5.setGeometry(QtCore.QRect(370, 10, 31, 61))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(300, 90, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(36)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(130, 150, 871, 21))
        self.line_6.setStyleSheet("")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setEnabled(True)
        self.widget_3.setGeometry(QtCore.QRect(890, 810, 911, 701))
        self.widget_3.setStyleSheet("background-color: rgb(44, 54, 57);")
        self.widget_3.setObjectName("widget_3")
        self.lineEditLogin = QtWidgets.QLineEdit(self.widget_3)
        self.lineEditLogin.setGeometry(QtCore.QRect(340, 300, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditLogin.setFont(font)
        self.lineEditLogin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditLogin.setObjectName("lineEditLogin")
        self.lineEditPassword = QtWidgets.QLineEdit(self.widget_3)
        self.lineEditPassword.setGeometry(QtCore.QRect(340, 360, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonAuthorization = QtWidgets.QPushButton(self.widget_3)
        self.pushButtonAuthorization.setGeometry(QtCore.QRect(330, 410, 281, 51))
        self.pushButtonAuthorization.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}")
        self.pushButtonAuthorization.setObjectName("pushButtonAuthorization")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(230, 290, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(251, 255, 242);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(220, 350, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(251, 255, 242);")
        self.label_7.setObjectName("label_7")
        self.widgetRoutes = QtWidgets.QWidget(self.centralwidget)
        self.widgetRoutes.setGeometry(QtCore.QRect(129, 79, 871, 721))
        self.widgetRoutes.setObjectName("widgetRoutes")
        self.label_19 = QtWidgets.QLabel(self.widgetRoutes)
        self.label_19.setGeometry(QtCore.QRect(100, 0, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.widgetRoutes)
        self.label_20.setGeometry(QtCore.QRect(10, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widgetRoutes)
        self.label_21.setGeometry(QtCore.QRect(10, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widgetRoutes)
        self.label_22.setGeometry(QtCore.QRect(10, 110, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.widgetRoutes)
        self.label_23.setGeometry(QtCore.QRect(10, 140, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widgetRoutes)
        self.label_24.setGeometry(QtCore.QRect(10, 170, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.widgetRoutes)
        self.label_25.setGeometry(QtCore.QRect(10, 200, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widgetRoutes)
        self.lineEdit_7.setGeometry(QtCore.QRect(200, 60, 181, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.line_11 = QtWidgets.QFrame(self.widgetRoutes)
        self.line_11.setGeometry(QtCore.QRect(173, 60, 20, 271))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widgetRoutes)
        self.lineEdit_8.setGeometry(QtCore.QRect(200, 90, 181, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widgetRoutes)
        self.lineEdit_9.setGeometry(QtCore.QRect(200, 120, 181, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widgetRoutes)
        self.lineEdit_10.setGeometry(QtCore.QRect(200, 150, 181, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widgetRoutes)
        self.lineEdit_11.setGeometry(QtCore.QRect(200, 180, 181, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widgetRoutes)
        self.lineEdit_12.setGeometry(QtCore.QRect(200, 210, 181, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.line_12 = QtWidgets.QFrame(self.widgetRoutes)
        self.line_12.setGeometry(QtCore.QRect(0, 35, 401, 21))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.widgetRoutes)
        self.line_13.setGeometry(QtCore.QRect(389, 0, 31, 331))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.pushButton_11 = QtWidgets.QPushButton(self.widgetRoutes)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 260, 121, 41))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}\n"
"\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.line_14 = QtWidgets.QFrame(self.widgetRoutes)
        self.line_14.setGeometry(QtCore.QRect(0, 320, 391, 16))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_26 = QtWidgets.QLabel(self.widgetRoutes)
        self.label_26.setGeometry(QtCore.QRect(520, 0, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.pushButton_12 = QtWidgets.QPushButton(self.widgetRoutes)
        self.pushButton_12.setGeometry(QtCore.QRect(570, 280, 121, 41))
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}\n"
"\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.graphicsView = QtWidgets.QGraphicsView(self.widgetRoutes)
        self.graphicsView.setGeometry(QtCore.QRect(0, 340, 871, 371))
        self.graphicsView.setObjectName("graphicsView")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widgetRoutes)
        self.lineEdit_13.setGeometry(QtCore.QRect(540, 70, 181, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widgetRoutes)
        self.lineEdit_14.setGeometry(QtCore.QRect(540, 110, 181, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widgetRoutes)
        self.lineEdit_15.setGeometry(QtCore.QRect(540, 150, 181, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widgetRoutes)
        self.lineEdit_16.setGeometry(QtCore.QRect(540, 190, 181, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.widgetRoutes)
        self.lineEdit_17.setGeometry(QtCore.QRect(540, 220, 181, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.widtegBus = QtWidgets.QWidget(self.centralwidget)
        self.widtegBus.setGeometry(QtCore.QRect(1030, 30, 871, 711))
        self.widtegBus.setObjectName("widtegBus")
        self.label_8 = QtWidgets.QLabel(self.widtegBus)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widtegBus)
        self.label_9.setGeometry(QtCore.QRect(20, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widtegBus)
        self.label_10.setGeometry(QtCore.QRect(20, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.line_7 = QtWidgets.QFrame(self.widtegBus)
        self.line_7.setGeometry(QtCore.QRect(270, 0, 21, 711))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.widtegBus)
        self.line_8.setGeometry(QtCore.QRect(0, 250, 871, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.widtegBus)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 200, 121, 41))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 3px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_11 = QtWidgets.QLabel(self.widtegBus)
        self.label_11.setGeometry(QtCore.QRect(440, 10, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_state_number = QtWidgets.QLineEdit(self.widtegBus)
        self.lineEdit_state_number.setGeometry(QtCore.QRect(430, 60, 221, 20))
        self.lineEdit_state_number.setObjectName("lineEdit_state_number")
        self.lineEdit_vin = QtWidgets.QLineEdit(self.widtegBus)
        self.lineEdit_vin.setGeometry(QtCore.QRect(430, 100, 221, 20))
        self.lineEdit_vin.setObjectName("lineEdit_vin")
        self.lineEdit_bus_model = QtWidgets.QLineEdit(self.widtegBus)
        self.lineEdit_bus_model.setGeometry(QtCore.QRect(430, 140, 221, 20))
        self.lineEdit_bus_model.setObjectName("lineEdit_bus_model")
        self.label_12 = QtWidgets.QLabel(self.widtegBus)
        self.label_12.setGeometry(QtCore.QRect(290, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widtegBus)
        self.label_13.setGeometry(QtCore.QRect(290, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.widtegBus)
        self.label_14.setGeometry(QtCore.QRect(290, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widtegBus)
        self.label_15.setGeometry(QtCore.QRect(290, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.widtegBus)
        self.label_16.setGeometry(QtCore.QRect(290, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.line_9 = QtWidgets.QFrame(self.widtegBus)
        self.line_9.setGeometry(QtCore.QRect(410, 0, 20, 261))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.lineEdit_bus_year = QtWidgets.QLineEdit(self.widtegBus)
        self.lineEdit_bus_year.setGeometry(QtCore.QRect(430, 180, 221, 20))
        self.lineEdit_bus_year.setObjectName("lineEdit_bus_year")
        self.lineEdit_odometer = QtWidgets.QLineEdit(self.widtegBus)
        self.lineEdit_odometer.setGeometry(QtCore.QRect(430, 220, 221, 20))
        self.lineEdit_odometer.setObjectName("lineEdit_odometer")
        self.pushButton_6 = QtWidgets.QPushButton(self.widtegBus)
        self.pushButton_6.setGeometry(QtCore.QRect(740, 210, 121, 41))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 3px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_17 = QtWidgets.QLabel(self.widtegBus)
        self.label_17.setGeometry(QtCore.QRect(120, 270, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.widtegBus)
        self.label_18.setGeometry(QtCore.QRect(10, 300, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lineEdit_vin_find = QtWidgets.QLineEdit(self.widtegBus)
        self.lineEdit_vin_find.setGeometry(QtCore.QRect(70, 320, 181, 20))
        self.lineEdit_vin_find.setObjectName("lineEdit_vin_find")
        self.pushButton_7 = QtWidgets.QPushButton(self.widtegBus)
        self.pushButton_7.setGeometry(QtCore.QRect(90, 360, 121, 41))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 3px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.line_10 = QtWidgets.QFrame(self.widtegBus)
        self.line_10.setGeometry(QtCore.QRect(0, 410, 871, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.tableWidget = QtWidgets.QTableWidget(self.widtegBus)
        self.tableWidget.setGeometry(QtCore.QRect(285, 271, 581, 141))
        self.tableWidget.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_8 = QtWidgets.QPushButton(self.widtegBus)
        self.pushButton_8.setGeometry(QtCore.QRect(300, 440, 161, 41))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 3px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.widtegBus)
        self.pushButton_9.setGeometry(QtCore.QRect(300, 490, 161, 41))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 3px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.widtegBus)
        self.pushButton_10.setGeometry(QtCore.QRect(470, 440, 211, 41))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 3px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}\n"
"\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(1810, 810, 851, 651))
        self.widget_5.setObjectName("widget_5")
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setGeometry(QtCore.QRect(30, 200, 251, 221))
        self.widget_6.setObjectName("widget_6")
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setGeometry(QtCore.QRect(480, 200, 251, 221))
        self.widget_7.setObjectName("widget_7")
        self.label_28 = QtWidgets.QLabel(self.widget_5)
        self.label_28.setGeometry(QtCore.QRect(350, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(10, 810, 871, 721))
        self.widget_4.setObjectName("widget_4")
        self.label_27 = QtWidgets.QLabel(self.widget_4)
        self.label_27.setGeometry(QtCore.QRect(330, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.widget_4)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 70, 851, 341))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 420, 141, 41))
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 70, 73);\n"
"    color: rgb(220, 220, 220);\n"
"    border: 1px solid rgb(68, 89, 90);\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    margin: 4px 8px;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 89, 90);\n"
"    color: rgb(246, 242, 235);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 72, 74);\n"
"    border: 1px solid rgb(50, 65, 66);\n"
"}\n"
"\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.line.raise_()
        self.line_2.raise_()
        self.widget.raise_()
        self.widget_2.raise_()
        self.label_5.raise_()
        self.line_6.raise_()
        self.widgetRoutes.raise_()
        self.widtegBus.raise_()
        self.widget_5.raise_()
        self.widget_3.raise_()
        self.widget_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Автобусы"))
        self.pushButton_2.setText(_translate("MainWindow", "Маршруты"))
        self.pushButton_3.setText(_translate("MainWindow", "Расписание"))
        self.pushButton_4.setText(_translate("MainWindow", "Аналитика"))
        self.pushButtonMain.setText(_translate("MainWindow", "Главная"))
        self.label.setText(_translate("MainWindow", "Bus Manager 1.0"))
        self.label_2.setText(_translate("MainWindow", "Welcome, user user"))
        self.label_3.setText(_translate("MainWindow", "message: 0"))
        self.label_4.setText(_translate("MainWindow", "help"))
        self.label_5.setText(_translate("MainWindow", "Сегодня 28.05.2025"))
        self.pushButtonAuthorization.setText(_translate("MainWindow", "Войти"))
        self.label_6.setText(_translate("MainWindow", "Логин"))
        self.label_7.setText(_translate("MainWindow", "Пароль"))
        self.label_19.setText(_translate("MainWindow", "Создать маршрут"))
        self.label_20.setText(_translate("MainWindow", "Название"))
        self.label_21.setText(_translate("MainWindow", "Номер"))
        self.label_22.setText(_translate("MainWindow", "Начальный пункт"))
        self.label_23.setText(_translate("MainWindow", "Пункт назначения"))
        self.label_24.setText(_translate("MainWindow", "Общее расстояние"))
        self.label_25.setText(_translate("MainWindow", "Время в пути"))
        self.pushButton_11.setText(_translate("MainWindow", "Создать"))
        self.label_26.setText(_translate("MainWindow", "Детализация маршрута"))
        self.pushButton_12.setText(_translate("MainWindow", "Подробнее"))
        self.label_8.setText(_translate("MainWindow", "Всего автобусов в парке: "))
        self.label_9.setText(_translate("MainWindow", "Исправных: "))
        self.label_10.setText(_translate("MainWindow", "В ремонте:"))
        self.pushButton_5.setText(_translate("MainWindow", "Подробнее"))
        self.label_11.setText(_translate("MainWindow", "Добавить новый автобус"))
        self.label_12.setText(_translate("MainWindow", "Гос.номер"))
        self.label_13.setText(_translate("MainWindow", "VIN"))
        self.label_14.setText(_translate("MainWindow", "Модель"))
        self.label_15.setText(_translate("MainWindow", "Год выпуска"))
        self.label_16.setText(_translate("MainWindow", "Пробег"))
        self.pushButton_6.setText(_translate("MainWindow", "Создать"))
        self.label_17.setText(_translate("MainWindow", "Поиск"))
        self.label_18.setText(_translate("MainWindow", "VIN"))
        self.pushButton_7.setText(_translate("MainWindow", "Найти"))
        self.pushButton_8.setText(_translate("MainWindow", "Отправить на ТО"))
        self.pushButton_9.setText(_translate("MainWindow", "Списать"))
        self.pushButton_10.setText(_translate("MainWindow", "Исторя обслуживания"))
        self.label_28.setText(_translate("MainWindow", "Аналитика"))
        self.label_27.setText(_translate("MainWindow", "Текущие рейсы"))
        self.pushButton_13.setText(_translate("MainWindow", "Запланировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
